# Generated by Django 5.1 on 2024-08-30 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('for_rent', 'For Rent'), ('for_sale', 'For Sale')], max_length=20)),
                ('street_address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('price', models.FloatField(max_length=100)),
                ('lot_size', models.FloatField(max_length=100)),
                ('story', models.IntegerField(max_length=2)),
                ('nr_rooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(blank=True, decimal_places=1, max_digits=2)),
                ('building_year', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
