# Generated by Django 5.1 on 2024-08-30 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_story'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='nr_rooms',
            new_name='number_of_rooms',
        ),
        migrations.AddField(
            model_name='listing',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(default='home_factory/static/img/no_photo.jpg', upload_to='images/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='listing',
            name='required_commission',
            field=models.FloatField(blank=True, default=0, max_length=100),
        ),
    ]
