# Generated by Django 5.1 on 2024-08-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_rename_nr_rooms_listing_number_of_rooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='photo_main',
            field=models.ImageField(default='./home_factory/static/img/no_photo.jpg', upload_to='images/%Y/%m/%d/'),
        ),
    ]
